version: "1.0"
info:
  model: int-scaffold
packages:
- name: MJAN24FebGit701Project
  gitServerName: MJANGit
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: MJANNormal120Asset
  version: "1.0"
  gitServerName: MJANGit
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: SIQACloudStreamsTestSAGWM
  version: "1.0"
  gitServerName: MJANGit
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: SIQACloudStreamsTestWM
  version: "1.0"
  gitServerName: MJANGit
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: SIQACloudStreamsTests
  gitServerName: MJANGit
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: sag_webmethods
configurationVariables:
  jdbcfunc.SAPTxStore.failFastMode: false
  jdbcfunc.SAPTxStore.connPoolAlias: SAP TxStore Pool
